services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      PROXY_PASS: http://app:8084

