services:
  app:
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://database:5432/dassco_asset_service
      POSTGRES_USERNAME: dassco_asset_service
      POSTGRES_PASSWORD: dassco_asset_service
      LIQUIBASE_CONTEXT: local
